### ISSUE TITLE
Allow pixel assignment based on input data ra, dec in ObsCondition

### ISSUE THREAD

**Issue by hangqianjun** [LSSTDESC/rail_astro_tools#15]
Currently, the `ObsCondition` randomly assigns the input galaxies into healpix pixels depending on the input survey footprint. I would like to add a functionality such that it will first check if the data contains `ra` and `dec` columns, and if so, use the observing conditions corresponding to these positions; in case there is no spatial coordinates, random assignment will be used. The output from ObsCondition attaches the pixel number of the galaxy to the input data; I would like to change this to `ra`, `decl`, such that the `Dereddener` can be run on the output.

**Comment by eacharles** [comment]
done in #21
