### ISSUE TITLE
add a module to merge close-by objects in catalog into blends

### ISSUE THREAD

**Issue by shuang92** [LSSTDESC/rail_astro_tools#9]
I'm interested in adding a degrader in rail that takes in a catalog of truth objects, identify possible unrecognized blends and merge those objects into one blended source. Some thoughts are needed for assigning the flux, size and shape for merged objects.

**Comment by shuang92** [comment]
merged branch from rail_astro_tools/issue/9/bl_degrader
https://github.com/LSSTDESC/rail_astro_tools/pull/44

**Comment by eacharles** [comment]
#59
